//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.OrderConfirmationWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderConfirmationViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderConfirmationViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShippingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private E_Shopper.OrderConfirmationWebService.OrderItem_OrderConfirmation[] OrderItem_OrderConfirmationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalAmountField, value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ShippingAddress {
            get {
                return this.ShippingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShippingAddressField, value) != true)) {
                    this.ShippingAddressField = value;
                    this.RaisePropertyChanged("ShippingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public E_Shopper.OrderConfirmationWebService.OrderItem_OrderConfirmation[] OrderItem_OrderConfirmations {
            get {
                return this.OrderItem_OrderConfirmationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderItem_OrderConfirmationsField, value) != true)) {
                    this.OrderItem_OrderConfirmationsField = value;
                    this.RaisePropertyChanged("OrderItem_OrderConfirmations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem_OrderConfirmation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderItem_OrderConfirmation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductImageURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityField, value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPriceField, value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProductImageURL {
            get {
                return this.ProductImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductImageURLField, value) != true)) {
                    this.ProductImageURLField = value;
                    this.RaisePropertyChanged("ProductImageURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderConfirmationWebService.OrderConfirmationServiceSoap")]
    public interface OrderConfirmationServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetOrderDetailsResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponse GetOrderDetails(E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponse> GetOrderDetailsAsync(E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetails", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequestBody Body;
        
        public GetOrderDetailsRequest() {
        }
        
        public GetOrderDetailsRequest(E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public GetOrderDetailsRequestBody() {
        }
        
        public GetOrderDetailsRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponseBody Body;
        
        public GetOrderDetailsResponse() {
        }
        
        public GetOrderDetailsResponse(E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.OrderConfirmationWebService.OrderConfirmationViewModel GetOrderDetailsResult;
        
        public GetOrderDetailsResponseBody() {
        }
        
        public GetOrderDetailsResponseBody(E_Shopper.OrderConfirmationWebService.OrderConfirmationViewModel GetOrderDetailsResult) {
            this.GetOrderDetailsResult = GetOrderDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderConfirmationServiceSoapChannel : E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderConfirmationServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap>, E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap {
        
        public OrderConfirmationServiceSoapClient() {
        }
        
        public OrderConfirmationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderConfirmationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderConfirmationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderConfirmationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponse E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap.GetOrderDetails(E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetails(request);
        }
        
        public E_Shopper.OrderConfirmationWebService.OrderConfirmationViewModel GetOrderDetails(int orderId) {
            E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest inValue = new E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest();
            inValue.Body = new E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponse retVal = ((E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap)(this)).GetOrderDetails(inValue);
            return retVal.Body.GetOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponse> E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap.GetOrderDetailsAsync(E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.OrderConfirmationWebService.GetOrderDetailsResponse> GetOrderDetailsAsync(int orderId) {
            E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest inValue = new E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequest();
            inValue.Body = new E_Shopper.OrderConfirmationWebService.GetOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            return ((E_Shopper.OrderConfirmationWebService.OrderConfirmationServiceSoap)(this)).GetOrderDetailsAsync(inValue);
        }
    }
}
