//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.AccountWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountViewModel", Namespace="http://yourwebsite.com/")]
    [System.SerializableAttribute()]
    public partial class AccountViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VCHUSERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHUSERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHPASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHEMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHROLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHACTIVEField;
        
        private System.DateTime DCREATEDATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHUSERID {
            get {
                return this.VCHUSERIDField;
            }
            set {
                if ((this.VCHUSERIDField.Equals(value) != true)) {
                    this.VCHUSERIDField = value;
                    this.RaisePropertyChanged("VCHUSERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VCHUSERNAME {
            get {
                return this.VCHUSERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHUSERNAMEField, value) != true)) {
                    this.VCHUSERNAMEField = value;
                    this.RaisePropertyChanged("VCHUSERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCHPASSWORD {
            get {
                return this.VCHPASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHPASSWORDField, value) != true)) {
                    this.VCHPASSWORDField = value;
                    this.RaisePropertyChanged("VCHPASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCHEMAIL {
            get {
                return this.VCHEMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHEMAILField, value) != true)) {
                    this.VCHEMAILField = value;
                    this.RaisePropertyChanged("VCHEMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VCHROLE {
            get {
                return this.VCHROLEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHROLEField, value) != true)) {
                    this.VCHROLEField = value;
                    this.RaisePropertyChanged("VCHROLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string VCHACTIVE {
            get {
                return this.VCHACTIVEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHACTIVEField, value) != true)) {
                    this.VCHACTIVEField = value;
                    this.RaisePropertyChanged("VCHACTIVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DCREATEDATE {
            get {
                return this.DCREATEDATEField;
            }
            set {
                if ((this.DCREATEDATEField.Equals(value) != true)) {
                    this.DCREATEDATEField = value;
                    this.RaisePropertyChanged("DCREATEDATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yourwebsite.com/", ConfigurationName="AccountWebService.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: 命名空間 http://yourwebsite.com/ 的元素名稱  username 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/GetUserByUsername", ReplyAction="*")]
        E_Shopper.AccountWebService.GetUserByUsernameResponse GetUserByUsername(E_Shopper.AccountWebService.GetUserByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/GetUserByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.AccountWebService.GetUserByUsernameResponse> GetUserByUsernameAsync(E_Shopper.AccountWebService.GetUserByUsernameRequest request);
        
        // CODEGEN: 命名空間 http://yourwebsite.com/ 的元素名稱  userinfo 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/ValidatePassword", ReplyAction="*")]
        E_Shopper.AccountWebService.ValidatePasswordResponse ValidatePassword(E_Shopper.AccountWebService.ValidatePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/ValidatePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.AccountWebService.ValidatePasswordResponse> ValidatePasswordAsync(E_Shopper.AccountWebService.ValidatePasswordRequest request);
        
        // CODEGEN: 命名空間 http://yourwebsite.com/ 的元素名稱  user 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/RegisterUser", ReplyAction="*")]
        E_Shopper.AccountWebService.RegisterUserResponse RegisterUser(E_Shopper.AccountWebService.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.AccountWebService.RegisterUserResponse> RegisterUserAsync(E_Shopper.AccountWebService.RegisterUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByUsername", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.AccountWebService.GetUserByUsernameRequestBody Body;
        
        public GetUserByUsernameRequest() {
        }
        
        public GetUserByUsernameRequest(E_Shopper.AccountWebService.GetUserByUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class GetUserByUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserByUsernameRequestBody() {
        }
        
        public GetUserByUsernameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByUsernameResponse", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.AccountWebService.GetUserByUsernameResponseBody Body;
        
        public GetUserByUsernameResponse() {
        }
        
        public GetUserByUsernameResponse(E_Shopper.AccountWebService.GetUserByUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class GetUserByUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.AccountWebService.AccountViewModel GetUserByUsernameResult;
        
        public GetUserByUsernameResponseBody() {
        }
        
        public GetUserByUsernameResponseBody(E_Shopper.AccountWebService.AccountViewModel GetUserByUsernameResult) {
            this.GetUserByUsernameResult = GetUserByUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidatePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidatePassword", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.AccountWebService.ValidatePasswordRequestBody Body;
        
        public ValidatePasswordRequest() {
        }
        
        public ValidatePasswordRequest(E_Shopper.AccountWebService.ValidatePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class ValidatePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.AccountWebService.AccountViewModel userinfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidatePasswordRequestBody() {
        }
        
        public ValidatePasswordRequestBody(E_Shopper.AccountWebService.AccountViewModel userinfo, string password) {
            this.userinfo = userinfo;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidatePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidatePasswordResponse", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.AccountWebService.ValidatePasswordResponseBody Body;
        
        public ValidatePasswordResponse() {
        }
        
        public ValidatePasswordResponse(E_Shopper.AccountWebService.ValidatePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class ValidatePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidatePasswordResult;
        
        public ValidatePasswordResponseBody() {
        }
        
        public ValidatePasswordResponseBody(bool ValidatePasswordResult) {
            this.ValidatePasswordResult = ValidatePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.AccountWebService.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(E_Shopper.AccountWebService.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.AccountWebService.AccountViewModel user;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(E_Shopper.AccountWebService.AccountViewModel user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.AccountWebService.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(E_Shopper.AccountWebService.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegisterUserResponseBody {
        
        public RegisterUserResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : E_Shopper.AccountWebService.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.AccountWebService.AccountServiceSoap>, E_Shopper.AccountWebService.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.AccountWebService.GetUserByUsernameResponse E_Shopper.AccountWebService.AccountServiceSoap.GetUserByUsername(E_Shopper.AccountWebService.GetUserByUsernameRequest request) {
            return base.Channel.GetUserByUsername(request);
        }
        
        public E_Shopper.AccountWebService.AccountViewModel GetUserByUsername(string username) {
            E_Shopper.AccountWebService.GetUserByUsernameRequest inValue = new E_Shopper.AccountWebService.GetUserByUsernameRequest();
            inValue.Body = new E_Shopper.AccountWebService.GetUserByUsernameRequestBody();
            inValue.Body.username = username;
            E_Shopper.AccountWebService.GetUserByUsernameResponse retVal = ((E_Shopper.AccountWebService.AccountServiceSoap)(this)).GetUserByUsername(inValue);
            return retVal.Body.GetUserByUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.AccountWebService.GetUserByUsernameResponse> E_Shopper.AccountWebService.AccountServiceSoap.GetUserByUsernameAsync(E_Shopper.AccountWebService.GetUserByUsernameRequest request) {
            return base.Channel.GetUserByUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.AccountWebService.GetUserByUsernameResponse> GetUserByUsernameAsync(string username) {
            E_Shopper.AccountWebService.GetUserByUsernameRequest inValue = new E_Shopper.AccountWebService.GetUserByUsernameRequest();
            inValue.Body = new E_Shopper.AccountWebService.GetUserByUsernameRequestBody();
            inValue.Body.username = username;
            return ((E_Shopper.AccountWebService.AccountServiceSoap)(this)).GetUserByUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.AccountWebService.ValidatePasswordResponse E_Shopper.AccountWebService.AccountServiceSoap.ValidatePassword(E_Shopper.AccountWebService.ValidatePasswordRequest request) {
            return base.Channel.ValidatePassword(request);
        }
        
        public bool ValidatePassword(E_Shopper.AccountWebService.AccountViewModel userinfo, string password) {
            E_Shopper.AccountWebService.ValidatePasswordRequest inValue = new E_Shopper.AccountWebService.ValidatePasswordRequest();
            inValue.Body = new E_Shopper.AccountWebService.ValidatePasswordRequestBody();
            inValue.Body.userinfo = userinfo;
            inValue.Body.password = password;
            E_Shopper.AccountWebService.ValidatePasswordResponse retVal = ((E_Shopper.AccountWebService.AccountServiceSoap)(this)).ValidatePassword(inValue);
            return retVal.Body.ValidatePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.AccountWebService.ValidatePasswordResponse> E_Shopper.AccountWebService.AccountServiceSoap.ValidatePasswordAsync(E_Shopper.AccountWebService.ValidatePasswordRequest request) {
            return base.Channel.ValidatePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.AccountWebService.ValidatePasswordResponse> ValidatePasswordAsync(E_Shopper.AccountWebService.AccountViewModel userinfo, string password) {
            E_Shopper.AccountWebService.ValidatePasswordRequest inValue = new E_Shopper.AccountWebService.ValidatePasswordRequest();
            inValue.Body = new E_Shopper.AccountWebService.ValidatePasswordRequestBody();
            inValue.Body.userinfo = userinfo;
            inValue.Body.password = password;
            return ((E_Shopper.AccountWebService.AccountServiceSoap)(this)).ValidatePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.AccountWebService.RegisterUserResponse E_Shopper.AccountWebService.AccountServiceSoap.RegisterUser(E_Shopper.AccountWebService.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public void RegisterUser(E_Shopper.AccountWebService.AccountViewModel user) {
            E_Shopper.AccountWebService.RegisterUserRequest inValue = new E_Shopper.AccountWebService.RegisterUserRequest();
            inValue.Body = new E_Shopper.AccountWebService.RegisterUserRequestBody();
            inValue.Body.user = user;
            E_Shopper.AccountWebService.RegisterUserResponse retVal = ((E_Shopper.AccountWebService.AccountServiceSoap)(this)).RegisterUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.AccountWebService.RegisterUserResponse> E_Shopper.AccountWebService.AccountServiceSoap.RegisterUserAsync(E_Shopper.AccountWebService.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.AccountWebService.RegisterUserResponse> RegisterUserAsync(E_Shopper.AccountWebService.AccountViewModel user) {
            E_Shopper.AccountWebService.RegisterUserRequest inValue = new E_Shopper.AccountWebService.RegisterUserRequest();
            inValue.Body = new E_Shopper.AccountWebService.RegisterUserRequestBody();
            inValue.Body.user = user;
            return ((E_Shopper.AccountWebService.AccountServiceSoap)(this)).RegisterUserAsync(inValue);
        }
    }
}
