//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.OrderCheckoutWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderCheckoutViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderCheckoutViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VCHCARTITEMIDField;
        
        private int VCHRPRODUCTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHQUANTITYField;
        
        private int VCHUSERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMAINIMAGEURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHCARTITEMID {
            get {
                return this.VCHCARTITEMIDField;
            }
            set {
                if ((this.VCHCARTITEMIDField.Equals(value) != true)) {
                    this.VCHCARTITEMIDField = value;
                    this.RaisePropertyChanged("VCHCARTITEMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHRPRODUCTID {
            get {
                return this.VCHRPRODUCTIDField;
            }
            set {
                if ((this.VCHRPRODUCTIDField.Equals(value) != true)) {
                    this.VCHRPRODUCTIDField = value;
                    this.RaisePropertyChanged("VCHRPRODUCTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCHQUANTITY {
            get {
                return this.VCHQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHQUANTITYField, value) != true)) {
                    this.VCHQUANTITYField = value;
                    this.RaisePropertyChanged("VCHQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int VCHUSERID {
            get {
                return this.VCHUSERIDField;
            }
            set {
                if ((this.VCHUSERIDField.Equals(value) != true)) {
                    this.VCHUSERIDField = value;
                    this.RaisePropertyChanged("VCHUSERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VCHRNAME {
            get {
                return this.VCHRNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRNAMEField, value) != true)) {
                    this.VCHRNAMEField = value;
                    this.RaisePropertyChanged("VCHRNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string VCHRPRICE {
            get {
                return this.VCHRPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRPRICEField, value) != true)) {
                    this.VCHRPRICEField = value;
                    this.RaisePropertyChanged("VCHRPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VCHRMAINIMAGEURL {
            get {
                return this.VCHRMAINIMAGEURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMAINIMAGEURLField, value) != true)) {
                    this.VCHRMAINIMAGEURLField = value;
                    this.RaisePropertyChanged("VCHRMAINIMAGEURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string totalField;
        
        private int productidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string price {
            get {
                return this.priceField;
            }
            set {
                if ((object.ReferenceEquals(this.priceField, value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((object.ReferenceEquals(this.quantityField, value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                if ((object.ReferenceEquals(this.totalField, value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int productid {
            get {
                return this.productidField;
            }
            set {
                if ((this.productidField.Equals(value) != true)) {
                    this.productidField = value;
                    this.RaisePropertyChanged("productid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderCheckoutWebService.OrderCheckoutServiceSoap")]
    public interface OrderCheckoutServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  selectedItems 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponse GetOrderDetails(E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponse> GetOrderDetailsAsync(E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  totalAmount 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrderToDatabase", ReplyAction="*")]
        E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponse SaveOrderToDatabase(E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrderToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponse> SaveOrderToDatabaseAsync(E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  orderItems 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrderDetailsToDatabase", ReplyAction="*")]
        E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponse SaveOrderDetailsToDatabase(E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveOrderDetailsToDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponse> SaveOrderDetailsToDatabaseAsync(E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetails", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequestBody Body;
        
        public GetOrderDetailsRequest() {
        }
        
        public GetOrderDetailsRequest(E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.OrderCheckoutWebService.ArrayOfString selectedItems;
        
        public GetOrderDetailsRequestBody() {
        }
        
        public GetOrderDetailsRequestBody(E_Shopper.OrderCheckoutWebService.ArrayOfString selectedItems) {
            this.selectedItems = selectedItems;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponseBody Body;
        
        public GetOrderDetailsResponse() {
        }
        
        public GetOrderDetailsResponse(E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.OrderCheckoutWebService.OrderCheckoutViewModel[] GetOrderDetailsResult;
        
        public GetOrderDetailsResponseBody() {
        }
        
        public GetOrderDetailsResponseBody(E_Shopper.OrderCheckoutWebService.OrderCheckoutViewModel[] GetOrderDetailsResult) {
            this.GetOrderDetailsResult = GetOrderDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderToDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrderToDatabase", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequestBody Body;
        
        public SaveOrderToDatabaseRequest() {
        }
        
        public SaveOrderToDatabaseRequest(E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrderToDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string totalAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string paymentMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string deliveryMethod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string shippingAddress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string orderNotes;
        
        public SaveOrderToDatabaseRequestBody() {
        }
        
        public SaveOrderToDatabaseRequestBody(int userId, string totalAmount, string paymentMethod, string deliveryMethod, string shippingAddress, string orderNotes) {
            this.userId = userId;
            this.totalAmount = totalAmount;
            this.paymentMethod = paymentMethod;
            this.deliveryMethod = deliveryMethod;
            this.shippingAddress = shippingAddress;
            this.orderNotes = orderNotes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderToDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrderToDatabaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponseBody Body;
        
        public SaveOrderToDatabaseResponse() {
        }
        
        public SaveOrderToDatabaseResponse(E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrderToDatabaseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveOrderToDatabaseResult;
        
        public SaveOrderToDatabaseResponseBody() {
        }
        
        public SaveOrderToDatabaseResponseBody(int SaveOrderToDatabaseResult) {
            this.SaveOrderToDatabaseResult = SaveOrderToDatabaseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderDetailsToDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrderDetailsToDatabase", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequestBody Body;
        
        public SaveOrderDetailsToDatabaseRequest() {
        }
        
        public SaveOrderDetailsToDatabaseRequest(E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveOrderDetailsToDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.OrderCheckoutWebService.OrderItem[] orderItems;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int newOrderId;
        
        public SaveOrderDetailsToDatabaseRequestBody() {
        }
        
        public SaveOrderDetailsToDatabaseRequestBody(E_Shopper.OrderCheckoutWebService.OrderItem[] orderItems, int newOrderId) {
            this.orderItems = orderItems;
            this.newOrderId = newOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveOrderDetailsToDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveOrderDetailsToDatabaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponseBody Body;
        
        public SaveOrderDetailsToDatabaseResponse() {
        }
        
        public SaveOrderDetailsToDatabaseResponse(E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveOrderDetailsToDatabaseResponseBody {
        
        public SaveOrderDetailsToDatabaseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderCheckoutServiceSoapChannel : E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderCheckoutServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap>, E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap {
        
        public OrderCheckoutServiceSoapClient() {
        }
        
        public OrderCheckoutServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderCheckoutServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderCheckoutServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderCheckoutServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponse E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap.GetOrderDetails(E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetails(request);
        }
        
        public E_Shopper.OrderCheckoutWebService.OrderCheckoutViewModel[] GetOrderDetails(E_Shopper.OrderCheckoutWebService.ArrayOfString selectedItems) {
            E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest inValue = new E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest();
            inValue.Body = new E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequestBody();
            inValue.Body.selectedItems = selectedItems;
            E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponse retVal = ((E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap)(this)).GetOrderDetails(inValue);
            return retVal.Body.GetOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponse> E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap.GetOrderDetailsAsync(E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.GetOrderDetailsResponse> GetOrderDetailsAsync(E_Shopper.OrderCheckoutWebService.ArrayOfString selectedItems) {
            E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest inValue = new E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequest();
            inValue.Body = new E_Shopper.OrderCheckoutWebService.GetOrderDetailsRequestBody();
            inValue.Body.selectedItems = selectedItems;
            return ((E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap)(this)).GetOrderDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponse E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap.SaveOrderToDatabase(E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest request) {
            return base.Channel.SaveOrderToDatabase(request);
        }
        
        public int SaveOrderToDatabase(int userId, string totalAmount, string paymentMethod, string deliveryMethod, string shippingAddress, string orderNotes) {
            E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest inValue = new E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest();
            inValue.Body = new E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.totalAmount = totalAmount;
            inValue.Body.paymentMethod = paymentMethod;
            inValue.Body.deliveryMethod = deliveryMethod;
            inValue.Body.shippingAddress = shippingAddress;
            inValue.Body.orderNotes = orderNotes;
            E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponse retVal = ((E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap)(this)).SaveOrderToDatabase(inValue);
            return retVal.Body.SaveOrderToDatabaseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponse> E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap.SaveOrderToDatabaseAsync(E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest request) {
            return base.Channel.SaveOrderToDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseResponse> SaveOrderToDatabaseAsync(int userId, string totalAmount, string paymentMethod, string deliveryMethod, string shippingAddress, string orderNotes) {
            E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest inValue = new E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequest();
            inValue.Body = new E_Shopper.OrderCheckoutWebService.SaveOrderToDatabaseRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.totalAmount = totalAmount;
            inValue.Body.paymentMethod = paymentMethod;
            inValue.Body.deliveryMethod = deliveryMethod;
            inValue.Body.shippingAddress = shippingAddress;
            inValue.Body.orderNotes = orderNotes;
            return ((E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap)(this)).SaveOrderToDatabaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponse E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap.SaveOrderDetailsToDatabase(E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest request) {
            return base.Channel.SaveOrderDetailsToDatabase(request);
        }
        
        public void SaveOrderDetailsToDatabase(E_Shopper.OrderCheckoutWebService.OrderItem[] orderItems, int newOrderId) {
            E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest inValue = new E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest();
            inValue.Body = new E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequestBody();
            inValue.Body.orderItems = orderItems;
            inValue.Body.newOrderId = newOrderId;
            E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponse retVal = ((E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap)(this)).SaveOrderDetailsToDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponse> E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap.SaveOrderDetailsToDatabaseAsync(E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest request) {
            return base.Channel.SaveOrderDetailsToDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseResponse> SaveOrderDetailsToDatabaseAsync(E_Shopper.OrderCheckoutWebService.OrderItem[] orderItems, int newOrderId) {
            E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest inValue = new E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequest();
            inValue.Body = new E_Shopper.OrderCheckoutWebService.SaveOrderDetailsToDatabaseRequestBody();
            inValue.Body.orderItems = orderItems;
            inValue.Body.newOrderId = newOrderId;
            return ((E_Shopper.OrderCheckoutWebService.OrderCheckoutServiceSoap)(this)).SaveOrderDetailsToDatabaseAsync(inValue);
        }
    }
}
