//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.ProductsWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductsViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VCHRPRODUCTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRDESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRCATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRBRANDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRDISCOUNTPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTOCKQUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRCOLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMAINIMAGEURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRTAGSField;
        
        private System.DateTime VCHRCREATEDATField;
        
        private System.DateTime VCHRUPDATEDATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRAVERAGERATINGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRREVIEWCOUNTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHRPRODUCTID {
            get {
                return this.VCHRPRODUCTIDField;
            }
            set {
                if ((this.VCHRPRODUCTIDField.Equals(value) != true)) {
                    this.VCHRPRODUCTIDField = value;
                    this.RaisePropertyChanged("VCHRPRODUCTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VCHRNAME {
            get {
                return this.VCHRNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRNAMEField, value) != true)) {
                    this.VCHRNAMEField = value;
                    this.RaisePropertyChanged("VCHRNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCHRDESCRIPTION {
            get {
                return this.VCHRDESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRDESCRIPTIONField, value) != true)) {
                    this.VCHRDESCRIPTIONField = value;
                    this.RaisePropertyChanged("VCHRDESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCHRCATEGORY {
            get {
                return this.VCHRCATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRCATEGORYField, value) != true)) {
                    this.VCHRCATEGORYField = value;
                    this.RaisePropertyChanged("VCHRCATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VCHRBRAND {
            get {
                return this.VCHRBRANDField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRBRANDField, value) != true)) {
                    this.VCHRBRANDField = value;
                    this.RaisePropertyChanged("VCHRBRAND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string VCHRPRICE {
            get {
                return this.VCHRPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRPRICEField, value) != true)) {
                    this.VCHRPRICEField = value;
                    this.RaisePropertyChanged("VCHRPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VCHRDISCOUNTPRICE {
            get {
                return this.VCHRDISCOUNTPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRDISCOUNTPRICEField, value) != true)) {
                    this.VCHRDISCOUNTPRICEField = value;
                    this.RaisePropertyChanged("VCHRDISCOUNTPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VCHRSTOCKQUANTITY {
            get {
                return this.VCHRSTOCKQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTOCKQUANTITYField, value) != true)) {
                    this.VCHRSTOCKQUANTITYField = value;
                    this.RaisePropertyChanged("VCHRSTOCKQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string VCHRCOLOR {
            get {
                return this.VCHRCOLORField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRCOLORField, value) != true)) {
                    this.VCHRCOLORField = value;
                    this.RaisePropertyChanged("VCHRCOLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string VCHRSIZE {
            get {
                return this.VCHRSIZEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSIZEField, value) != true)) {
                    this.VCHRSIZEField = value;
                    this.RaisePropertyChanged("VCHRSIZE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string VCHRMATERIAL {
            get {
                return this.VCHRMATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMATERIALField, value) != true)) {
                    this.VCHRMATERIALField = value;
                    this.RaisePropertyChanged("VCHRMATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VCHRMAINIMAGEURL {
            get {
                return this.VCHRMAINIMAGEURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMAINIMAGEURLField, value) != true)) {
                    this.VCHRMAINIMAGEURLField = value;
                    this.RaisePropertyChanged("VCHRMAINIMAGEURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VCHRSTATUS {
            get {
                return this.VCHRSTATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTATUSField, value) != true)) {
                    this.VCHRSTATUSField = value;
                    this.RaisePropertyChanged("VCHRSTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string VCHRTAGS {
            get {
                return this.VCHRTAGSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRTAGSField, value) != true)) {
                    this.VCHRTAGSField = value;
                    this.RaisePropertyChanged("VCHRTAGS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime VCHRCREATEDAT {
            get {
                return this.VCHRCREATEDATField;
            }
            set {
                if ((this.VCHRCREATEDATField.Equals(value) != true)) {
                    this.VCHRCREATEDATField = value;
                    this.RaisePropertyChanged("VCHRCREATEDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime VCHRUPDATEDAT {
            get {
                return this.VCHRUPDATEDATField;
            }
            set {
                if ((this.VCHRUPDATEDATField.Equals(value) != true)) {
                    this.VCHRUPDATEDATField = value;
                    this.RaisePropertyChanged("VCHRUPDATEDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string VCHRAVERAGERATING {
            get {
                return this.VCHRAVERAGERATINGField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRAVERAGERATINGField, value) != true)) {
                    this.VCHRAVERAGERATINGField = value;
                    this.RaisePropertyChanged("VCHRAVERAGERATING");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string VCHRREVIEWCOUNT {
            get {
                return this.VCHRREVIEWCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRREVIEWCOUNTField, value) != true)) {
                    this.VCHRREVIEWCOUNTField = value;
                    this.RaisePropertyChanged("VCHRREVIEWCOUNT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsWebService.ProductsServiceSoap")]
    public interface ProductsServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetProductsResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        E_Shopper.ProductsWebService.GetProductsResponse GetProducts(E_Shopper.ProductsWebService.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.GetProductsResponse> GetProductsAsync(E_Shopper.ProductsWebService.GetProductsRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  product 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        E_Shopper.ProductsWebService.AddProductResponse AddProduct(E_Shopper.ProductsWebService.AddProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.AddProductResponse> AddProductAsync(E_Shopper.ProductsWebService.AddProductRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  productId 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatus", ReplyAction="*")]
        E_Shopper.ProductsWebService.UpdateStatusResponse UpdateStatus(E_Shopper.ProductsWebService.UpdateStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateStatusResponse> UpdateStatusAsync(E_Shopper.ProductsWebService.UpdateStatusRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  product 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        E_Shopper.ProductsWebService.UpdateProductResponse UpdateProduct(E_Shopper.ProductsWebService.UpdateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateProductResponse> UpdateProductAsync(E_Shopper.ProductsWebService.UpdateProductRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  product 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductImage", ReplyAction="*")]
        E_Shopper.ProductsWebService.UpdateProductImageResponse UpdateProductImage(E_Shopper.ProductsWebService.UpdateProductImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductImage", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateProductImageResponse> UpdateProductImageAsync(E_Shopper.ProductsWebService.UpdateProductImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        void DeleteProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProduct", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteProductAsync(int productId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(E_Shopper.ProductsWebService.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody {
        
        public GetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(E_Shopper.ProductsWebService.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.ProductsWebService.ProductsViewModel[] GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(E_Shopper.ProductsWebService.ProductsViewModel[] GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProduct", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.AddProductRequestBody Body;
        
        public AddProductRequest() {
        }
        
        public AddProductRequest(E_Shopper.ProductsWebService.AddProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.ProductsWebService.ProductsViewModel product;
        
        public AddProductRequestBody() {
        }
        
        public AddProductRequestBody(E_Shopper.ProductsWebService.ProductsViewModel product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.AddProductResponseBody Body;
        
        public AddProductResponse() {
        }
        
        public AddProductResponse(E_Shopper.ProductsWebService.AddProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddProductResponseBody {
        
        public AddProductResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStatus", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.UpdateStatusRequestBody Body;
        
        public UpdateStatusRequest() {
        }
        
        public UpdateStatusRequest(E_Shopper.ProductsWebService.UpdateStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public UpdateStatusRequestBody() {
        }
        
        public UpdateStatusRequestBody(string productId, string status) {
            this.productId = productId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.UpdateStatusResponseBody Body;
        
        public UpdateStatusResponse() {
        }
        
        public UpdateStatusResponse(E_Shopper.ProductsWebService.UpdateStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateStatusResponseBody {
        
        public UpdateStatusResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProduct", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.UpdateProductRequestBody Body;
        
        public UpdateProductRequest() {
        }
        
        public UpdateProductRequest(E_Shopper.ProductsWebService.UpdateProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.ProductsWebService.ProductsViewModel product;
        
        public UpdateProductRequestBody() {
        }
        
        public UpdateProductRequestBody(E_Shopper.ProductsWebService.ProductsViewModel product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.UpdateProductResponseBody Body;
        
        public UpdateProductResponse() {
        }
        
        public UpdateProductResponse(E_Shopper.ProductsWebService.UpdateProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductResponseBody {
        
        public UpdateProductResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductImage", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.UpdateProductImageRequestBody Body;
        
        public UpdateProductImageRequest() {
        }
        
        public UpdateProductImageRequest(E_Shopper.ProductsWebService.UpdateProductImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.ProductsWebService.ProductsViewModel product;
        
        public UpdateProductImageRequestBody() {
        }
        
        public UpdateProductImageRequestBody(E_Shopper.ProductsWebService.ProductsViewModel product) {
            this.product = product;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsWebService.UpdateProductImageResponseBody Body;
        
        public UpdateProductImageResponse() {
        }
        
        public UpdateProductImageResponse(E_Shopper.ProductsWebService.UpdateProductImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateProductImageResponseBody {
        
        public UpdateProductImageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductsServiceSoapChannel : E_Shopper.ProductsWebService.ProductsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.ProductsWebService.ProductsServiceSoap>, E_Shopper.ProductsWebService.ProductsServiceSoap {
        
        public ProductsServiceSoapClient() {
        }
        
        public ProductsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsWebService.GetProductsResponse E_Shopper.ProductsWebService.ProductsServiceSoap.GetProducts(E_Shopper.ProductsWebService.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public E_Shopper.ProductsWebService.ProductsViewModel[] GetProducts() {
            E_Shopper.ProductsWebService.GetProductsRequest inValue = new E_Shopper.ProductsWebService.GetProductsRequest();
            inValue.Body = new E_Shopper.ProductsWebService.GetProductsRequestBody();
            E_Shopper.ProductsWebService.GetProductsResponse retVal = ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.GetProductsResponse> E_Shopper.ProductsWebService.ProductsServiceSoap.GetProductsAsync(E_Shopper.ProductsWebService.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsWebService.GetProductsResponse> GetProductsAsync() {
            E_Shopper.ProductsWebService.GetProductsRequest inValue = new E_Shopper.ProductsWebService.GetProductsRequest();
            inValue.Body = new E_Shopper.ProductsWebService.GetProductsRequestBody();
            return ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).GetProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsWebService.AddProductResponse E_Shopper.ProductsWebService.ProductsServiceSoap.AddProduct(E_Shopper.ProductsWebService.AddProductRequest request) {
            return base.Channel.AddProduct(request);
        }
        
        public void AddProduct(E_Shopper.ProductsWebService.ProductsViewModel product) {
            E_Shopper.ProductsWebService.AddProductRequest inValue = new E_Shopper.ProductsWebService.AddProductRequest();
            inValue.Body = new E_Shopper.ProductsWebService.AddProductRequestBody();
            inValue.Body.product = product;
            E_Shopper.ProductsWebService.AddProductResponse retVal = ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).AddProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.AddProductResponse> E_Shopper.ProductsWebService.ProductsServiceSoap.AddProductAsync(E_Shopper.ProductsWebService.AddProductRequest request) {
            return base.Channel.AddProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsWebService.AddProductResponse> AddProductAsync(E_Shopper.ProductsWebService.ProductsViewModel product) {
            E_Shopper.ProductsWebService.AddProductRequest inValue = new E_Shopper.ProductsWebService.AddProductRequest();
            inValue.Body = new E_Shopper.ProductsWebService.AddProductRequestBody();
            inValue.Body.product = product;
            return ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).AddProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsWebService.UpdateStatusResponse E_Shopper.ProductsWebService.ProductsServiceSoap.UpdateStatus(E_Shopper.ProductsWebService.UpdateStatusRequest request) {
            return base.Channel.UpdateStatus(request);
        }
        
        public void UpdateStatus(string productId, string status) {
            E_Shopper.ProductsWebService.UpdateStatusRequest inValue = new E_Shopper.ProductsWebService.UpdateStatusRequest();
            inValue.Body = new E_Shopper.ProductsWebService.UpdateStatusRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.status = status;
            E_Shopper.ProductsWebService.UpdateStatusResponse retVal = ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).UpdateStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateStatusResponse> E_Shopper.ProductsWebService.ProductsServiceSoap.UpdateStatusAsync(E_Shopper.ProductsWebService.UpdateStatusRequest request) {
            return base.Channel.UpdateStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateStatusResponse> UpdateStatusAsync(string productId, string status) {
            E_Shopper.ProductsWebService.UpdateStatusRequest inValue = new E_Shopper.ProductsWebService.UpdateStatusRequest();
            inValue.Body = new E_Shopper.ProductsWebService.UpdateStatusRequestBody();
            inValue.Body.productId = productId;
            inValue.Body.status = status;
            return ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).UpdateStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsWebService.UpdateProductResponse E_Shopper.ProductsWebService.ProductsServiceSoap.UpdateProduct(E_Shopper.ProductsWebService.UpdateProductRequest request) {
            return base.Channel.UpdateProduct(request);
        }
        
        public void UpdateProduct(E_Shopper.ProductsWebService.ProductsViewModel product) {
            E_Shopper.ProductsWebService.UpdateProductRequest inValue = new E_Shopper.ProductsWebService.UpdateProductRequest();
            inValue.Body = new E_Shopper.ProductsWebService.UpdateProductRequestBody();
            inValue.Body.product = product;
            E_Shopper.ProductsWebService.UpdateProductResponse retVal = ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).UpdateProduct(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateProductResponse> E_Shopper.ProductsWebService.ProductsServiceSoap.UpdateProductAsync(E_Shopper.ProductsWebService.UpdateProductRequest request) {
            return base.Channel.UpdateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateProductResponse> UpdateProductAsync(E_Shopper.ProductsWebService.ProductsViewModel product) {
            E_Shopper.ProductsWebService.UpdateProductRequest inValue = new E_Shopper.ProductsWebService.UpdateProductRequest();
            inValue.Body = new E_Shopper.ProductsWebService.UpdateProductRequestBody();
            inValue.Body.product = product;
            return ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).UpdateProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsWebService.UpdateProductImageResponse E_Shopper.ProductsWebService.ProductsServiceSoap.UpdateProductImage(E_Shopper.ProductsWebService.UpdateProductImageRequest request) {
            return base.Channel.UpdateProductImage(request);
        }
        
        public void UpdateProductImage(E_Shopper.ProductsWebService.ProductsViewModel product) {
            E_Shopper.ProductsWebService.UpdateProductImageRequest inValue = new E_Shopper.ProductsWebService.UpdateProductImageRequest();
            inValue.Body = new E_Shopper.ProductsWebService.UpdateProductImageRequestBody();
            inValue.Body.product = product;
            E_Shopper.ProductsWebService.UpdateProductImageResponse retVal = ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).UpdateProductImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateProductImageResponse> E_Shopper.ProductsWebService.ProductsServiceSoap.UpdateProductImageAsync(E_Shopper.ProductsWebService.UpdateProductImageRequest request) {
            return base.Channel.UpdateProductImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsWebService.UpdateProductImageResponse> UpdateProductImageAsync(E_Shopper.ProductsWebService.ProductsViewModel product) {
            E_Shopper.ProductsWebService.UpdateProductImageRequest inValue = new E_Shopper.ProductsWebService.UpdateProductImageRequest();
            inValue.Body = new E_Shopper.ProductsWebService.UpdateProductImageRequestBody();
            inValue.Body.product = product;
            return ((E_Shopper.ProductsWebService.ProductsServiceSoap)(this)).UpdateProductImageAsync(inValue);
        }
        
        public void DeleteProduct(int productId) {
            base.Channel.DeleteProduct(productId);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int productId) {
            return base.Channel.DeleteProductAsync(productId);
        }
    }
}
