//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.HomeWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HomeViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HomeViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VCHRPRODUCTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRDESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRCATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRBRANDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRDISCOUNTPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTOCKQUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRCOLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMAINIMAGEURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRTAGSField;
        
        private System.DateTime VCHRCREATEDATField;
        
        private System.DateTime VCHRUPDATEDATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRAVERAGERATINGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRREVIEWCOUNTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHRPRODUCTID {
            get {
                return this.VCHRPRODUCTIDField;
            }
            set {
                if ((this.VCHRPRODUCTIDField.Equals(value) != true)) {
                    this.VCHRPRODUCTIDField = value;
                    this.RaisePropertyChanged("VCHRPRODUCTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VCHRNAME {
            get {
                return this.VCHRNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRNAMEField, value) != true)) {
                    this.VCHRNAMEField = value;
                    this.RaisePropertyChanged("VCHRNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCHRDESCRIPTION {
            get {
                return this.VCHRDESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRDESCRIPTIONField, value) != true)) {
                    this.VCHRDESCRIPTIONField = value;
                    this.RaisePropertyChanged("VCHRDESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCHRCATEGORY {
            get {
                return this.VCHRCATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRCATEGORYField, value) != true)) {
                    this.VCHRCATEGORYField = value;
                    this.RaisePropertyChanged("VCHRCATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VCHRBRAND {
            get {
                return this.VCHRBRANDField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRBRANDField, value) != true)) {
                    this.VCHRBRANDField = value;
                    this.RaisePropertyChanged("VCHRBRAND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string VCHRPRICE {
            get {
                return this.VCHRPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRPRICEField, value) != true)) {
                    this.VCHRPRICEField = value;
                    this.RaisePropertyChanged("VCHRPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VCHRDISCOUNTPRICE {
            get {
                return this.VCHRDISCOUNTPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRDISCOUNTPRICEField, value) != true)) {
                    this.VCHRDISCOUNTPRICEField = value;
                    this.RaisePropertyChanged("VCHRDISCOUNTPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VCHRSTOCKQUANTITY {
            get {
                return this.VCHRSTOCKQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTOCKQUANTITYField, value) != true)) {
                    this.VCHRSTOCKQUANTITYField = value;
                    this.RaisePropertyChanged("VCHRSTOCKQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string VCHRCOLOR {
            get {
                return this.VCHRCOLORField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRCOLORField, value) != true)) {
                    this.VCHRCOLORField = value;
                    this.RaisePropertyChanged("VCHRCOLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string VCHRSIZE {
            get {
                return this.VCHRSIZEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSIZEField, value) != true)) {
                    this.VCHRSIZEField = value;
                    this.RaisePropertyChanged("VCHRSIZE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string VCHRMATERIAL {
            get {
                return this.VCHRMATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMATERIALField, value) != true)) {
                    this.VCHRMATERIALField = value;
                    this.RaisePropertyChanged("VCHRMATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VCHRMAINIMAGEURL {
            get {
                return this.VCHRMAINIMAGEURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMAINIMAGEURLField, value) != true)) {
                    this.VCHRMAINIMAGEURLField = value;
                    this.RaisePropertyChanged("VCHRMAINIMAGEURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VCHRSTATUS {
            get {
                return this.VCHRSTATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTATUSField, value) != true)) {
                    this.VCHRSTATUSField = value;
                    this.RaisePropertyChanged("VCHRSTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string VCHRTAGS {
            get {
                return this.VCHRTAGSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRTAGSField, value) != true)) {
                    this.VCHRTAGSField = value;
                    this.RaisePropertyChanged("VCHRTAGS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime VCHRCREATEDAT {
            get {
                return this.VCHRCREATEDATField;
            }
            set {
                if ((this.VCHRCREATEDATField.Equals(value) != true)) {
                    this.VCHRCREATEDATField = value;
                    this.RaisePropertyChanged("VCHRCREATEDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime VCHRUPDATEDAT {
            get {
                return this.VCHRUPDATEDATField;
            }
            set {
                if ((this.VCHRUPDATEDATField.Equals(value) != true)) {
                    this.VCHRUPDATEDATField = value;
                    this.RaisePropertyChanged("VCHRUPDATEDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string VCHRAVERAGERATING {
            get {
                return this.VCHRAVERAGERATINGField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRAVERAGERATINGField, value) != true)) {
                    this.VCHRAVERAGERATINGField = value;
                    this.RaisePropertyChanged("VCHRAVERAGERATING");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string VCHRREVIEWCOUNT {
            get {
                return this.VCHRREVIEWCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRREVIEWCOUNTField, value) != true)) {
                    this.VCHRREVIEWCOUNTField = value;
                    this.RaisePropertyChanged("VCHRREVIEWCOUNT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryCountViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoryCountViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        private int CountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HomeWebService.HomeServiceSoap")]
    public interface HomeServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetProductsResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        E_Shopper.HomeWebService.GetProductsResponse GetProducts(E_Shopper.HomeWebService.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetProductsResponse> GetProductsAsync(E_Shopper.HomeWebService.GetProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToCartInDatabase", ReplyAction="*")]
        void AddToCartInDatabase(int userId, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToCartInDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task AddToCartInDatabaseAsync(int userId, int productId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsProductInCart", ReplyAction="*")]
        bool IsProductInCart(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsProductInCart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsProductInCartAsync(int userId, int productId);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetCategoriesWithCountResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategoriesWithCount", ReplyAction="*")]
        E_Shopper.HomeWebService.GetCategoriesWithCountResponse GetCategoriesWithCount(E_Shopper.HomeWebService.GetCategoriesWithCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategoriesWithCount", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetCategoriesWithCountResponse> GetCategoriesWithCountAsync(E_Shopper.HomeWebService.GetCategoriesWithCountRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  category 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByCategory", ReplyAction="*")]
        E_Shopper.HomeWebService.GetProductsByCategoryResponse GetProductsByCategory(E_Shopper.HomeWebService.GetProductsByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductsByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetProductsByCategoryResponse> GetProductsByCategoryAsync(E_Shopper.HomeWebService.GetProductsByCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProducts", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.HomeWebService.GetProductsRequestBody Body;
        
        public GetProductsRequest() {
        }
        
        public GetProductsRequest(E_Shopper.HomeWebService.GetProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductsRequestBody {
        
        public GetProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.HomeWebService.GetProductsResponseBody Body;
        
        public GetProductsResponse() {
        }
        
        public GetProductsResponse(E_Shopper.HomeWebService.GetProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.HomeWebService.HomeViewModel[] GetProductsResult;
        
        public GetProductsResponseBody() {
        }
        
        public GetProductsResponseBody(E_Shopper.HomeWebService.HomeViewModel[] GetProductsResult) {
            this.GetProductsResult = GetProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesWithCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesWithCount", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.HomeWebService.GetCategoriesWithCountRequestBody Body;
        
        public GetCategoriesWithCountRequest() {
        }
        
        public GetCategoriesWithCountRequest(E_Shopper.HomeWebService.GetCategoriesWithCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesWithCountRequestBody {
        
        public GetCategoriesWithCountRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesWithCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesWithCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.HomeWebService.GetCategoriesWithCountResponseBody Body;
        
        public GetCategoriesWithCountResponse() {
        }
        
        public GetCategoriesWithCountResponse(E_Shopper.HomeWebService.GetCategoriesWithCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCategoriesWithCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.HomeWebService.CategoryCountViewModel[] GetCategoriesWithCountResult;
        
        public GetCategoriesWithCountResponseBody() {
        }
        
        public GetCategoriesWithCountResponseBody(E_Shopper.HomeWebService.CategoryCountViewModel[] GetCategoriesWithCountResult) {
            this.GetCategoriesWithCountResult = GetCategoriesWithCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByCategory", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.HomeWebService.GetProductsByCategoryRequestBody Body;
        
        public GetProductsByCategoryRequest() {
        }
        
        public GetProductsByCategoryRequest(E_Shopper.HomeWebService.GetProductsByCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public GetProductsByCategoryRequestBody() {
        }
        
        public GetProductsByCategoryRequestBody(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductsByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductsByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.HomeWebService.GetProductsByCategoryResponseBody Body;
        
        public GetProductsByCategoryResponse() {
        }
        
        public GetProductsByCategoryResponse(E_Shopper.HomeWebService.GetProductsByCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductsByCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.HomeWebService.HomeViewModel[] GetProductsByCategoryResult;
        
        public GetProductsByCategoryResponseBody() {
        }
        
        public GetProductsByCategoryResponseBody(E_Shopper.HomeWebService.HomeViewModel[] GetProductsByCategoryResult) {
            this.GetProductsByCategoryResult = GetProductsByCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HomeServiceSoapChannel : E_Shopper.HomeWebService.HomeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HomeServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.HomeWebService.HomeServiceSoap>, E_Shopper.HomeWebService.HomeServiceSoap {
        
        public HomeServiceSoapClient() {
        }
        
        public HomeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HomeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HomeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.HomeWebService.GetProductsResponse E_Shopper.HomeWebService.HomeServiceSoap.GetProducts(E_Shopper.HomeWebService.GetProductsRequest request) {
            return base.Channel.GetProducts(request);
        }
        
        public E_Shopper.HomeWebService.HomeViewModel[] GetProducts() {
            E_Shopper.HomeWebService.GetProductsRequest inValue = new E_Shopper.HomeWebService.GetProductsRequest();
            inValue.Body = new E_Shopper.HomeWebService.GetProductsRequestBody();
            E_Shopper.HomeWebService.GetProductsResponse retVal = ((E_Shopper.HomeWebService.HomeServiceSoap)(this)).GetProducts(inValue);
            return retVal.Body.GetProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetProductsResponse> E_Shopper.HomeWebService.HomeServiceSoap.GetProductsAsync(E_Shopper.HomeWebService.GetProductsRequest request) {
            return base.Channel.GetProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetProductsResponse> GetProductsAsync() {
            E_Shopper.HomeWebService.GetProductsRequest inValue = new E_Shopper.HomeWebService.GetProductsRequest();
            inValue.Body = new E_Shopper.HomeWebService.GetProductsRequestBody();
            return ((E_Shopper.HomeWebService.HomeServiceSoap)(this)).GetProductsAsync(inValue);
        }
        
        public void AddToCartInDatabase(int userId, int productId, int quantity) {
            base.Channel.AddToCartInDatabase(userId, productId, quantity);
        }
        
        public System.Threading.Tasks.Task AddToCartInDatabaseAsync(int userId, int productId, int quantity) {
            return base.Channel.AddToCartInDatabaseAsync(userId, productId, quantity);
        }
        
        public bool IsProductInCart(int userId, int productId) {
            return base.Channel.IsProductInCart(userId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> IsProductInCartAsync(int userId, int productId) {
            return base.Channel.IsProductInCartAsync(userId, productId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.HomeWebService.GetCategoriesWithCountResponse E_Shopper.HomeWebService.HomeServiceSoap.GetCategoriesWithCount(E_Shopper.HomeWebService.GetCategoriesWithCountRequest request) {
            return base.Channel.GetCategoriesWithCount(request);
        }
        
        public E_Shopper.HomeWebService.CategoryCountViewModel[] GetCategoriesWithCount() {
            E_Shopper.HomeWebService.GetCategoriesWithCountRequest inValue = new E_Shopper.HomeWebService.GetCategoriesWithCountRequest();
            inValue.Body = new E_Shopper.HomeWebService.GetCategoriesWithCountRequestBody();
            E_Shopper.HomeWebService.GetCategoriesWithCountResponse retVal = ((E_Shopper.HomeWebService.HomeServiceSoap)(this)).GetCategoriesWithCount(inValue);
            return retVal.Body.GetCategoriesWithCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetCategoriesWithCountResponse> E_Shopper.HomeWebService.HomeServiceSoap.GetCategoriesWithCountAsync(E_Shopper.HomeWebService.GetCategoriesWithCountRequest request) {
            return base.Channel.GetCategoriesWithCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetCategoriesWithCountResponse> GetCategoriesWithCountAsync() {
            E_Shopper.HomeWebService.GetCategoriesWithCountRequest inValue = new E_Shopper.HomeWebService.GetCategoriesWithCountRequest();
            inValue.Body = new E_Shopper.HomeWebService.GetCategoriesWithCountRequestBody();
            return ((E_Shopper.HomeWebService.HomeServiceSoap)(this)).GetCategoriesWithCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.HomeWebService.GetProductsByCategoryResponse E_Shopper.HomeWebService.HomeServiceSoap.GetProductsByCategory(E_Shopper.HomeWebService.GetProductsByCategoryRequest request) {
            return base.Channel.GetProductsByCategory(request);
        }
        
        public E_Shopper.HomeWebService.HomeViewModel[] GetProductsByCategory(string category) {
            E_Shopper.HomeWebService.GetProductsByCategoryRequest inValue = new E_Shopper.HomeWebService.GetProductsByCategoryRequest();
            inValue.Body = new E_Shopper.HomeWebService.GetProductsByCategoryRequestBody();
            inValue.Body.category = category;
            E_Shopper.HomeWebService.GetProductsByCategoryResponse retVal = ((E_Shopper.HomeWebService.HomeServiceSoap)(this)).GetProductsByCategory(inValue);
            return retVal.Body.GetProductsByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetProductsByCategoryResponse> E_Shopper.HomeWebService.HomeServiceSoap.GetProductsByCategoryAsync(E_Shopper.HomeWebService.GetProductsByCategoryRequest request) {
            return base.Channel.GetProductsByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.HomeWebService.GetProductsByCategoryResponse> GetProductsByCategoryAsync(string category) {
            E_Shopper.HomeWebService.GetProductsByCategoryRequest inValue = new E_Shopper.HomeWebService.GetProductsByCategoryRequest();
            inValue.Body = new E_Shopper.HomeWebService.GetProductsByCategoryRequestBody();
            inValue.Body.category = category;
            return ((E_Shopper.HomeWebService.HomeServiceSoap)(this)).GetProductsByCategoryAsync(inValue);
        }
    }
}
