//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.CartWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartViewModel", Namespace="http://yourwebsite.com/")]
    [System.SerializableAttribute()]
    public partial class CartViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VCHCARTITEMIDField;
        
        private int VCHRPRODUCTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHQUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTOCKQUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMAINIMAGEURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHCARTITEMID {
            get {
                return this.VCHCARTITEMIDField;
            }
            set {
                if ((this.VCHCARTITEMIDField.Equals(value) != true)) {
                    this.VCHCARTITEMIDField = value;
                    this.RaisePropertyChanged("VCHCARTITEMID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHRPRODUCTID {
            get {
                return this.VCHRPRODUCTIDField;
            }
            set {
                if ((this.VCHRPRODUCTIDField.Equals(value) != true)) {
                    this.VCHRPRODUCTIDField = value;
                    this.RaisePropertyChanged("VCHRPRODUCTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCHQUANTITY {
            get {
                return this.VCHQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHQUANTITYField, value) != true)) {
                    this.VCHQUANTITYField = value;
                    this.RaisePropertyChanged("VCHQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCHRNAME {
            get {
                return this.VCHRNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRNAMEField, value) != true)) {
                    this.VCHRNAMEField = value;
                    this.RaisePropertyChanged("VCHRNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VCHRPRICE {
            get {
                return this.VCHRPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRPRICEField, value) != true)) {
                    this.VCHRPRICEField = value;
                    this.RaisePropertyChanged("VCHRPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string VCHRSTOCKQUANTITY {
            get {
                return this.VCHRSTOCKQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTOCKQUANTITYField, value) != true)) {
                    this.VCHRSTOCKQUANTITYField = value;
                    this.RaisePropertyChanged("VCHRSTOCKQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VCHRMAINIMAGEURL {
            get {
                return this.VCHRMAINIMAGEURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMAINIMAGEURLField, value) != true)) {
                    this.VCHRMAINIMAGEURLField = value;
                    this.RaisePropertyChanged("VCHRMAINIMAGEURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yourwebsite.com/", ConfigurationName="CartWebService.CartServiceSoap")]
    public interface CartServiceSoap {
        
        // CODEGEN: 命名空間 http://yourwebsite.com/ 的元素名稱  GetCartbyUserIdResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/GetCartbyUserId", ReplyAction="*")]
        E_Shopper.CartWebService.GetCartbyUserIdResponse GetCartbyUserId(E_Shopper.CartWebService.GetCartbyUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/GetCartbyUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.CartWebService.GetCartbyUserIdResponse> GetCartbyUserIdAsync(E_Shopper.CartWebService.GetCartbyUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/DeletebyCartItemId", ReplyAction="*")]
        void DeletebyCartItemId(int cartitemid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/DeletebyCartItemId", ReplyAction="*")]
        System.Threading.Tasks.Task DeletebyCartItemIdAsync(int cartitemid);
        
        // CODEGEN: 命名空間 http://yourwebsite.com/ 的元素名稱  quantity 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/UpdateCartItemQuantity", ReplyAction="*")]
        E_Shopper.CartWebService.UpdateCartItemQuantityResponse UpdateCartItemQuantity(E_Shopper.CartWebService.UpdateCartItemQuantityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://yourwebsite.com/UpdateCartItemQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.CartWebService.UpdateCartItemQuantityResponse> UpdateCartItemQuantityAsync(E_Shopper.CartWebService.UpdateCartItemQuantityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCartbyUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCartbyUserId", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.CartWebService.GetCartbyUserIdRequestBody Body;
        
        public GetCartbyUserIdRequest() {
        }
        
        public GetCartbyUserIdRequest(E_Shopper.CartWebService.GetCartbyUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class GetCartbyUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userid;
        
        public GetCartbyUserIdRequestBody() {
        }
        
        public GetCartbyUserIdRequestBody(int userid) {
            this.userid = userid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCartbyUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCartbyUserIdResponse", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.CartWebService.GetCartbyUserIdResponseBody Body;
        
        public GetCartbyUserIdResponse() {
        }
        
        public GetCartbyUserIdResponse(E_Shopper.CartWebService.GetCartbyUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class GetCartbyUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.CartWebService.CartViewModel[] GetCartbyUserIdResult;
        
        public GetCartbyUserIdResponseBody() {
        }
        
        public GetCartbyUserIdResponseBody(E_Shopper.CartWebService.CartViewModel[] GetCartbyUserIdResult) {
            this.GetCartbyUserIdResult = GetCartbyUserIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCartItemQuantityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCartItemQuantity", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.CartWebService.UpdateCartItemQuantityRequestBody Body;
        
        public UpdateCartItemQuantityRequest() {
        }
        
        public UpdateCartItemQuantityRequest(E_Shopper.CartWebService.UpdateCartItemQuantityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://yourwebsite.com/")]
    public partial class UpdateCartItemQuantityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cartItemId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string quantity;
        
        public UpdateCartItemQuantityRequestBody() {
        }
        
        public UpdateCartItemQuantityRequestBody(int cartItemId, string quantity) {
            this.cartItemId = cartItemId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCartItemQuantityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCartItemQuantityResponse", Namespace="http://yourwebsite.com/", Order=0)]
        public E_Shopper.CartWebService.UpdateCartItemQuantityResponseBody Body;
        
        public UpdateCartItemQuantityResponse() {
        }
        
        public UpdateCartItemQuantityResponse(E_Shopper.CartWebService.UpdateCartItemQuantityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCartItemQuantityResponseBody {
        
        public UpdateCartItemQuantityResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CartServiceSoapChannel : E_Shopper.CartWebService.CartServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.CartWebService.CartServiceSoap>, E_Shopper.CartWebService.CartServiceSoap {
        
        public CartServiceSoapClient() {
        }
        
        public CartServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.CartWebService.GetCartbyUserIdResponse E_Shopper.CartWebService.CartServiceSoap.GetCartbyUserId(E_Shopper.CartWebService.GetCartbyUserIdRequest request) {
            return base.Channel.GetCartbyUserId(request);
        }
        
        public E_Shopper.CartWebService.CartViewModel[] GetCartbyUserId(int userid) {
            E_Shopper.CartWebService.GetCartbyUserIdRequest inValue = new E_Shopper.CartWebService.GetCartbyUserIdRequest();
            inValue.Body = new E_Shopper.CartWebService.GetCartbyUserIdRequestBody();
            inValue.Body.userid = userid;
            E_Shopper.CartWebService.GetCartbyUserIdResponse retVal = ((E_Shopper.CartWebService.CartServiceSoap)(this)).GetCartbyUserId(inValue);
            return retVal.Body.GetCartbyUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.CartWebService.GetCartbyUserIdResponse> E_Shopper.CartWebService.CartServiceSoap.GetCartbyUserIdAsync(E_Shopper.CartWebService.GetCartbyUserIdRequest request) {
            return base.Channel.GetCartbyUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.CartWebService.GetCartbyUserIdResponse> GetCartbyUserIdAsync(int userid) {
            E_Shopper.CartWebService.GetCartbyUserIdRequest inValue = new E_Shopper.CartWebService.GetCartbyUserIdRequest();
            inValue.Body = new E_Shopper.CartWebService.GetCartbyUserIdRequestBody();
            inValue.Body.userid = userid;
            return ((E_Shopper.CartWebService.CartServiceSoap)(this)).GetCartbyUserIdAsync(inValue);
        }
        
        public void DeletebyCartItemId(int cartitemid) {
            base.Channel.DeletebyCartItemId(cartitemid);
        }
        
        public System.Threading.Tasks.Task DeletebyCartItemIdAsync(int cartitemid) {
            return base.Channel.DeletebyCartItemIdAsync(cartitemid);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.CartWebService.UpdateCartItemQuantityResponse E_Shopper.CartWebService.CartServiceSoap.UpdateCartItemQuantity(E_Shopper.CartWebService.UpdateCartItemQuantityRequest request) {
            return base.Channel.UpdateCartItemQuantity(request);
        }
        
        public void UpdateCartItemQuantity(int cartItemId, string quantity) {
            E_Shopper.CartWebService.UpdateCartItemQuantityRequest inValue = new E_Shopper.CartWebService.UpdateCartItemQuantityRequest();
            inValue.Body = new E_Shopper.CartWebService.UpdateCartItemQuantityRequestBody();
            inValue.Body.cartItemId = cartItemId;
            inValue.Body.quantity = quantity;
            E_Shopper.CartWebService.UpdateCartItemQuantityResponse retVal = ((E_Shopper.CartWebService.CartServiceSoap)(this)).UpdateCartItemQuantity(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.CartWebService.UpdateCartItemQuantityResponse> E_Shopper.CartWebService.CartServiceSoap.UpdateCartItemQuantityAsync(E_Shopper.CartWebService.UpdateCartItemQuantityRequest request) {
            return base.Channel.UpdateCartItemQuantityAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.CartWebService.UpdateCartItemQuantityResponse> UpdateCartItemQuantityAsync(int cartItemId, string quantity) {
            E_Shopper.CartWebService.UpdateCartItemQuantityRequest inValue = new E_Shopper.CartWebService.UpdateCartItemQuantityRequest();
            inValue.Body = new E_Shopper.CartWebService.UpdateCartItemQuantityRequestBody();
            inValue.Body.cartItemId = cartItemId;
            inValue.Body.quantity = quantity;
            return ((E_Shopper.CartWebService.CartServiceSoap)(this)).UpdateCartItemQuantityAsync(inValue);
        }
    }
}
