//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Shopper.ProductsDetailWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsDetailViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductsDetailViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VCHRPRODUCTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRDESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRCATEGORYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRBRANDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRDISCOUNTPRICEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTOCKQUANTITYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRCOLORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSIZEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRMAINIMAGEURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRSTATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRTAGSField;
        
        private System.DateTime VCHRCREATEDATField;
        
        private System.DateTime VCHRUPDATEDATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRAVERAGERATINGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VCHRREVIEWCOUNTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VCHRPRODUCTID {
            get {
                return this.VCHRPRODUCTIDField;
            }
            set {
                if ((this.VCHRPRODUCTIDField.Equals(value) != true)) {
                    this.VCHRPRODUCTIDField = value;
                    this.RaisePropertyChanged("VCHRPRODUCTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string VCHRNAME {
            get {
                return this.VCHRNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRNAMEField, value) != true)) {
                    this.VCHRNAMEField = value;
                    this.RaisePropertyChanged("VCHRNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VCHRDESCRIPTION {
            get {
                return this.VCHRDESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRDESCRIPTIONField, value) != true)) {
                    this.VCHRDESCRIPTIONField = value;
                    this.RaisePropertyChanged("VCHRDESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string VCHRCATEGORY {
            get {
                return this.VCHRCATEGORYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRCATEGORYField, value) != true)) {
                    this.VCHRCATEGORYField = value;
                    this.RaisePropertyChanged("VCHRCATEGORY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string VCHRBRAND {
            get {
                return this.VCHRBRANDField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRBRANDField, value) != true)) {
                    this.VCHRBRANDField = value;
                    this.RaisePropertyChanged("VCHRBRAND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string VCHRPRICE {
            get {
                return this.VCHRPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRPRICEField, value) != true)) {
                    this.VCHRPRICEField = value;
                    this.RaisePropertyChanged("VCHRPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string VCHRDISCOUNTPRICE {
            get {
                return this.VCHRDISCOUNTPRICEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRDISCOUNTPRICEField, value) != true)) {
                    this.VCHRDISCOUNTPRICEField = value;
                    this.RaisePropertyChanged("VCHRDISCOUNTPRICE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string VCHRSTOCKQUANTITY {
            get {
                return this.VCHRSTOCKQUANTITYField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTOCKQUANTITYField, value) != true)) {
                    this.VCHRSTOCKQUANTITYField = value;
                    this.RaisePropertyChanged("VCHRSTOCKQUANTITY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string VCHRCOLOR {
            get {
                return this.VCHRCOLORField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRCOLORField, value) != true)) {
                    this.VCHRCOLORField = value;
                    this.RaisePropertyChanged("VCHRCOLOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string VCHRSIZE {
            get {
                return this.VCHRSIZEField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSIZEField, value) != true)) {
                    this.VCHRSIZEField = value;
                    this.RaisePropertyChanged("VCHRSIZE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string VCHRMATERIAL {
            get {
                return this.VCHRMATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMATERIALField, value) != true)) {
                    this.VCHRMATERIALField = value;
                    this.RaisePropertyChanged("VCHRMATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VCHRMAINIMAGEURL {
            get {
                return this.VCHRMAINIMAGEURLField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRMAINIMAGEURLField, value) != true)) {
                    this.VCHRMAINIMAGEURLField = value;
                    this.RaisePropertyChanged("VCHRMAINIMAGEURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VCHRSTATUS {
            get {
                return this.VCHRSTATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRSTATUSField, value) != true)) {
                    this.VCHRSTATUSField = value;
                    this.RaisePropertyChanged("VCHRSTATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string VCHRTAGS {
            get {
                return this.VCHRTAGSField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRTAGSField, value) != true)) {
                    this.VCHRTAGSField = value;
                    this.RaisePropertyChanged("VCHRTAGS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.DateTime VCHRCREATEDAT {
            get {
                return this.VCHRCREATEDATField;
            }
            set {
                if ((this.VCHRCREATEDATField.Equals(value) != true)) {
                    this.VCHRCREATEDATField = value;
                    this.RaisePropertyChanged("VCHRCREATEDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.DateTime VCHRUPDATEDAT {
            get {
                return this.VCHRUPDATEDATField;
            }
            set {
                if ((this.VCHRUPDATEDATField.Equals(value) != true)) {
                    this.VCHRUPDATEDATField = value;
                    this.RaisePropertyChanged("VCHRUPDATEDAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string VCHRAVERAGERATING {
            get {
                return this.VCHRAVERAGERATINGField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRAVERAGERATINGField, value) != true)) {
                    this.VCHRAVERAGERATINGField = value;
                    this.RaisePropertyChanged("VCHRAVERAGERATING");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string VCHRREVIEWCOUNT {
            get {
                return this.VCHRREVIEWCOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.VCHRREVIEWCOUNTField, value) != true)) {
                    this.VCHRREVIEWCOUNTField = value;
                    this.RaisePropertyChanged("VCHRREVIEWCOUNT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsDetailWebService.ProductsDetailServiceSoap")]
    public interface ProductsDetailServiceSoap {
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  GetProductByIdResult 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductById", ReplyAction="*")]
        E_Shopper.ProductsDetailWebService.GetProductByIdResponse GetProductById(E_Shopper.ProductsDetailWebService.GetProductByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProductById", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsDetailWebService.GetProductByIdResponse> GetProductByIdAsync(E_Shopper.ProductsDetailWebService.GetProductByIdRequest request);
        
        // CODEGEN: 命名空間 http://tempuri.org/ 的元素名稱  quantity 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToCartInDatabase", ReplyAction="*")]
        E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponse AddToCartInDatabase(E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToCartInDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponse> AddToCartInDatabaseAsync(E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsProductInCart", ReplyAction="*")]
        bool IsProductInCart(int userId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsProductInCart", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsProductInCartAsync(int userId, int productId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductById", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsDetailWebService.GetProductByIdRequestBody Body;
        
        public GetProductByIdRequest() {
        }
        
        public GetProductByIdRequest(E_Shopper.ProductsDetailWebService.GetProductByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetProductByIdRequestBody() {
        }
        
        public GetProductByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsDetailWebService.GetProductByIdResponseBody Body;
        
        public GetProductByIdResponse() {
        }
        
        public GetProductByIdResponse(E_Shopper.ProductsDetailWebService.GetProductByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public E_Shopper.ProductsDetailWebService.ProductsDetailViewModel GetProductByIdResult;
        
        public GetProductByIdResponseBody() {
        }
        
        public GetProductByIdResponseBody(E_Shopper.ProductsDetailWebService.ProductsDetailViewModel GetProductByIdResult) {
            this.GetProductByIdResult = GetProductByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToCartInDatabaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToCartInDatabase", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequestBody Body;
        
        public AddToCartInDatabaseRequest() {
        }
        
        public AddToCartInDatabaseRequest(E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddToCartInDatabaseRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string quantity;
        
        public AddToCartInDatabaseRequestBody() {
        }
        
        public AddToCartInDatabaseRequestBody(int userId, int productId, string quantity) {
            this.userId = userId;
            this.productId = productId;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToCartInDatabaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToCartInDatabaseResponse", Namespace="http://tempuri.org/", Order=0)]
        public E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponseBody Body;
        
        public AddToCartInDatabaseResponse() {
        }
        
        public AddToCartInDatabaseResponse(E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddToCartInDatabaseResponseBody {
        
        public AddToCartInDatabaseResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductsDetailServiceSoapChannel : E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsDetailServiceSoapClient : System.ServiceModel.ClientBase<E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap>, E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap {
        
        public ProductsDetailServiceSoapClient() {
        }
        
        public ProductsDetailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsDetailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsDetailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsDetailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsDetailWebService.GetProductByIdResponse E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap.GetProductById(E_Shopper.ProductsDetailWebService.GetProductByIdRequest request) {
            return base.Channel.GetProductById(request);
        }
        
        public E_Shopper.ProductsDetailWebService.ProductsDetailViewModel GetProductById(int id) {
            E_Shopper.ProductsDetailWebService.GetProductByIdRequest inValue = new E_Shopper.ProductsDetailWebService.GetProductByIdRequest();
            inValue.Body = new E_Shopper.ProductsDetailWebService.GetProductByIdRequestBody();
            inValue.Body.id = id;
            E_Shopper.ProductsDetailWebService.GetProductByIdResponse retVal = ((E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap)(this)).GetProductById(inValue);
            return retVal.Body.GetProductByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsDetailWebService.GetProductByIdResponse> E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap.GetProductByIdAsync(E_Shopper.ProductsDetailWebService.GetProductByIdRequest request) {
            return base.Channel.GetProductByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsDetailWebService.GetProductByIdResponse> GetProductByIdAsync(int id) {
            E_Shopper.ProductsDetailWebService.GetProductByIdRequest inValue = new E_Shopper.ProductsDetailWebService.GetProductByIdRequest();
            inValue.Body = new E_Shopper.ProductsDetailWebService.GetProductByIdRequestBody();
            inValue.Body.id = id;
            return ((E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap)(this)).GetProductByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponse E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap.AddToCartInDatabase(E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest request) {
            return base.Channel.AddToCartInDatabase(request);
        }
        
        public void AddToCartInDatabase(int userId, int productId, string quantity) {
            E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest inValue = new E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest();
            inValue.Body = new E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.productId = productId;
            inValue.Body.quantity = quantity;
            E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponse retVal = ((E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap)(this)).AddToCartInDatabase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponse> E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap.AddToCartInDatabaseAsync(E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest request) {
            return base.Channel.AddToCartInDatabaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<E_Shopper.ProductsDetailWebService.AddToCartInDatabaseResponse> AddToCartInDatabaseAsync(int userId, int productId, string quantity) {
            E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest inValue = new E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequest();
            inValue.Body = new E_Shopper.ProductsDetailWebService.AddToCartInDatabaseRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.productId = productId;
            inValue.Body.quantity = quantity;
            return ((E_Shopper.ProductsDetailWebService.ProductsDetailServiceSoap)(this)).AddToCartInDatabaseAsync(inValue);
        }
        
        public bool IsProductInCart(int userId, int productId) {
            return base.Channel.IsProductInCart(userId, productId);
        }
        
        public System.Threading.Tasks.Task<bool> IsProductInCartAsync(int userId, int productId) {
            return base.Channel.IsProductInCartAsync(userId, productId);
        }
    }
}
